name: Update Repo Count Badge

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:    

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get repo count from GitHub API
        id: repo_count
        run: |
          count=$(curl -s -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/users/XNS-ivy/repos?per_page=1" \
          | jq '. | length')
          echo "repo_count=$count" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          sed -i "s/Repositories: [0-9]\+/Repositories: ${{ steps.repo_count.outputs.repo_count }}/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update repo count badge"
          git push
        continue-on-error: true